import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Pause, Play, RotateCcw, ShieldCheck, Upload } from "lucide-react";
import { api } from "../lib/api";
import { useWsQuery } from "../lib/hooks";
import { useSession } from "../lib/session";
import { fmtNum, fmtRelative, fmtTime } from "../lib/format";
import type { IncidentBrief } from "../lib/types";
import { Card, Empty, ErrorState, Loading, RiskMeter, SeverityBadge, Stat, StatusBadge, useToast } from "../components/ui";
import { EventsOverTime, HBar, SeverityBars } from "../components/charts";

function Onboarding() {
  const { refreshMe, switchWorkspace } = useSession();
  const navigate = useNavigate();
  const toast = useToast();
  const [busy, setBusy] = useState(false);
  const openDemo = async () => {
    setBusy(true);
    try {
      const r = await api<{ workspace: { id: number }; created: boolean; stats: Record<string, number> | null }>("/api/workspaces/demo", { method: "POST" });
      await refreshMe();
      switchWorkspace(r.workspace.id);
      if (r.stats) toast(`Demo loaded: ${r.stats.accepted} synthetic events, ${r.stats.detections_created} detections, ${r.stats.incidents_created} incidents generated by the engine.`);
      navigate("/");
    } catch (e) {
      toast((e as Error).message, "error");
    } finally {
      setBusy(false);
    }
  };
  return (
    <div className="stack">
      <div className="page-head"><div><h1>Welcome to SentinelX</h1><p>This workspace has no telemetry yet. Choose how to start.</p></div></div>
      <div className="grid grid-2">
        <Card title="DEMO MODE — Nova Bank" sub="Synthetic environment for exploring the platform">
          <p className="text-2">Creates a separate demo workspace and generates seven days of synthetic Nova Bank telemetry (logins, processes, PowerShell,
            file access, privilege changes, network transfers) containing several attack scenarios. The data goes through the real pipeline — every detection
            and incident you will see is produced by the engines, not pre-written.</p>
          <button className="btn btn-primary mt-8" onClick={openDemo} disabled={busy}><ShieldCheck /> {busy ? "Generating & analysing…" : "Open Nova Bank demo"}</button>
        </Card>
        <Card title="ANALYST MODE — your data" sub="CSV or JSON security telemetry">
          <p className="text-2">Upload your own logs. SentinelX validates, normalizes (alternate field names, Windows event codes, ECS JSON), stores,
            runs detection, anomaly analysis and correlation, and reports exactly how many events, detections and incidents resulted.</p>
          <Link className="btn btn-primary mt-8" to="/ingest"><Upload /> Upload security data</Link>
        </Card>
      </div>
    </div>
  );
}

function SimulationCard() {
  const { isAnalyst, isAdmin } = useSession();
  const qc = useQueryClient();
  const toast = useToast();
  const sim = useWsQuery<{ available: boolean; running: boolean; ticks: number; events_generated: number; last_tick: string | null; tick_seconds: number; last_error: string | null }>(
    ["simulation"], "/api/simulation", { refetchInterval: 5000 });
  const act = useMutation({
    mutationFn: (action: string) => api(`/api/simulation/${action}`, { method: "POST" }),
    onSuccess: (_d, action) => { qc.invalidateQueries({ queryKey: ["ws"] }); qc.invalidateQueries({ queryKey: ["workspace"] }); toast(`Simulation ${action} requested.`); },
    onError: (e) => toast((e as Error).message, "error"),
  });
  if (!sim.data?.available) return null;
  const s = sim.data;
  return (
    <Card title="Live simulation" sub={`Streams synthetic events every ${s.tick_seconds}s through the real pipeline`}
      actions={isAnalyst && (
        <>
          {s.running ? <button className="btn btn-sm" onClick={() => act.mutate("pause")}><Pause /> Pause</button>
            : <button className="btn btn-sm" onClick={() => act.mutate("start")}><Play /> Start</button>}
          {isAdmin && <button className="btn btn-sm" onClick={() => confirm("Reset demo data and regenerate the baseline dataset?") && act.mutate("reset")}><RotateCcw /> Reset</button>}
        </>
      )}>
      <div className="row small">
        <span className={`badge ${s.running ? "st-ok" : ""}`}>{s.running ? "RUNNING" : "PAUSED"}</span>
        <span className="muted">{s.ticks} ticks · {fmtNum(s.events_generated)} events generated · last tick {fmtRelative(s.last_tick)}</span>
        {s.last_error && <span className="badge st-bad">Error: {s.last_error}</span>}
      </div>
    </Card>
  );
}

export function Dashboard() {
  const { workspace } = useSession();
  const navigate = useNavigate();
  const summary = useWsQuery<any>(["analytics", "summary"], "/api/analytics/summary", { refetchInterval: 30_000 });
  if (!workspace) return <Loading />;
  if (workspace.counts.events === 0) return <Onboarding />;
  if (summary.isLoading) return <Loading />;
  if (summary.error) return <ErrorState error={summary.error} onRetry={() => summary.refetch()} />;
  const s = summary.data;
  const k = s.kpis;
  const stats = workspace.last_pipeline_stats || {};
  return (
    <div className="stack">
      <div className="page-head">
        <div><h1>Security overview</h1><p>{workspace.name} · data from {fmtTime(s.range.start, false)} to {fmtTime(s.range.end, false)} UTC</p></div>
        <div className="page-actions">
          <Link className="btn" to="/ingest"><Upload /> Upload data</Link>
          <Link className="btn btn-primary" to="/incidents">Open incidents</Link>
        </div>
      </div>
      <div className="grid grid-4">
        <Stat label="Events analysed" value={fmtNum(k.events)} foot={`${fmtNum(k.users)} users · ${fmtNum(k.hosts)} hosts`} />
        <Stat label="Detections" value={fmtNum(k.detections)} foot={`${s.detections_by_rule.length} rules fired`} />
        <Stat label="Open incidents" value={fmtNum(k.open_incidents)} foot={<>{k.critical_open} critical{k.mean_risk_open !== null && ` · mean risk ${k.mean_risk_open}`}</>} />
        <Stat label="Anomalous behavior windows" value={fmtNum(k.anomalous_windows)} foot={`of ${fmtNum(k.anomaly_windows)} entity-days scored`} />
      </div>
      <div className="grid grid-main-side">
        <Card title="Events over time" sub={`Bucketed every ${s.range.bucket_hours} h, stacked by severity`}>
          <EventsOverTime data={s.events_over_time} />
        </Card>
        <Card title="Detections by severity"><SeverityBars data={s.detections_by_severity} label="Detections by severity" />
          <div className="small muted mt-8">Last analysis {fmtRelative(workspace.last_pipeline_run_at)}: {stats.rules_run ?? 0} rules over {fmtNum(stats.events_scanned)} events
            {stats.isolation_forest_used ? ", Isolation Forest scored behavior windows" : ""} ({stats.duration_ms ?? 0} ms).</div>
        </Card>
      </div>
      <SimulationCard />
      <Card title="Highest-risk incidents" actions={<Link to="/incidents" className="small">View all</Link>} flush>
        {s.recent_incidents.length === 0 ? <Empty title="No incidents">Detections have not correlated into incidents.</Empty> : (
          <div className="table-wrap">
            <table className="table responsive">
              <thead><tr><th>Incident</th><th>Severity</th><th>Risk</th><th>Status</th><th>Entities</th><th>Last seen (UTC)</th></tr></thead>
              <tbody>
                {s.recent_incidents.map((i: IncidentBrief) => (
                  <tr key={i.id} className="clickable" onClick={() => navigate(`/incidents/${i.id}`)}>
                    <td data-label="Incident"><Link to={`/incidents/${i.id}`} onClick={(e) => e.stopPropagation()}><strong>{i.number}</strong></Link> <span className="text-2">{i.title}</span></td>
                    <td data-label="Severity"><SeverityBadge severity={i.severity} /></td>
                    <td data-label="Risk"><RiskMeter score={i.risk_score} band={i.risk_band} /></td>
                    <td data-label="Status"><StatusBadge status={i.status} /></td>
                    <td data-label="Entities" className="small">{i.users.slice(0, 2).join(", ")}{i.users.length > 2 && ` +${i.users.length - 2}`}<br /><span className="muted">{i.hosts.slice(0, 2).join(", ")}</span></td>
                    <td data-label="Last seen" className="nowrap small">{fmtTime(i.last_seen, false)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
      <div className="grid grid-3">
        <Card title="Top users by events"><HBar data={s.top_users.slice(0, 8)} label="Top users by event count" onSelect={(u) => navigate(`/entities/user/${u}`)} /></Card>
        <Card title="Top hosts by events"><HBar data={s.top_hosts.slice(0, 8)} label="Top hosts by event count" onSelect={(h) => navigate(`/entities/host/${h}`)} /></Card>
        <Card title="Detections by rule"><HBar data={s.detections_by_rule.slice(0, 10)} label="Detections by rule" onSelect={(r) => navigate(`/detections?rule_key=${r}`)} /></Card>
      </div>
    </div>
  );
}
