"""Controlled seed process for a shared Nova Bank demo workspace with three role-based demo accounts.

Usage:  python -m app.seed [--reset]
Passwords come from SEED_DEMO_PASSWORD; if unset, a random one is generated and printed once.
All seeded telemetry is SYNTHETIC (fictional organization "Nova Bank").
"""

import argparse
import os
import secrets
import sys

from app.core.security import hash_password, password_problems
from app.database import session as dbs
from app.models import User, Workspace
from app.models.identity import MODE_DEMO, ROLE_ADMIN, ROLE_ANALYST, ROLE_VIEWER
from app.services.workspace import (
    add_member,
    bootstrap_reference_data,
    create_workspace,
    load_demo_data,
    reset_workspace_data,
)

ACCOUNTS = [("admin@novabank.demo", "Nova Admin", ROLE_ADMIN), ("analyst@novabank.demo", "Nova Analyst", ROLE_ANALYST),
            ("viewer@novabank.demo", "Nova Viewer", ROLE_VIEWER)]
WORKSPACE_NAME = "Nova Bank SOC (Shared Demo)"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reset", action="store_true", help="regenerate the demo telemetry if it already exists")
    args = parser.parse_args()
    password = os.environ.get("SEED_DEMO_PASSWORD") or secrets.token_urlsafe(12) + "7a"
    problems = password_problems(password)
    if problems:
        print(f"SEED_DEMO_PASSWORD must contain {', '.join(problems)}", file=sys.stderr)
        return 2
    db = dbs.SessionLocal()
    try:
        bootstrap_reference_data(db)
        users = []
        for email, name, _ in ACCOUNTS:
            u = db.query(User).filter_by(email=email).first()
            if u is None:
                u = User(email=email, full_name=name, password_hash=hash_password(password), settings={"theme": "dark"})
                db.add(u)
                db.flush()
            users.append(u)
        ws = db.query(Workspace).filter_by(name=WORKSPACE_NAME, mode=MODE_DEMO).first()
        fresh = ws is None
        if fresh:
            ws = create_workspace(db, WORKSPACE_NAME, users[0], MODE_DEMO)
        for u, (_, _, role) in zip(users, ACCOUNTS, strict=True):
            add_member(db, ws, u, role)
        db.commit()
        if fresh or args.reset:
            if not fresh:
                reset_workspace_data(db, ws.id)
                db.commit()
            stats = load_demo_data(db, ws)
            db.commit()
            print(f"Seeded {stats['accepted']} synthetic events -> {stats['detections_created']} detections, "
                  f"{stats['incidents_created']} incidents (generated by the pipeline).")
        else:
            print("Demo workspace already exists (use --reset to regenerate telemetry).")
        print("Demo accounts:", ", ".join(f"{e} ({r})" for e, _, r in ACCOUNTS))
        if not os.environ.get("SEED_DEMO_PASSWORD"):
            print(f"Generated password for new demo accounts: {password}")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    raise SystemExit(main())
