"""Write the synthetic sample datasets and the event schema to ./datasets.

Usage (from the repository root):  backend/.venv/bin/python scripts/export_samples.py
All data is SYNTHETIC telemetry for the fictional organization "Nova Bank".
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.demo.generator import DATASETS, dataset_records, to_csv, to_json  # noqa: E402

OUT = ROOT / "datasets"


def main() -> None:
    OUT.mkdir(exist_ok=True)
    lines = ["# SentinelX sample datasets (synthetic)", "",
             "Fictional Nova Bank telemetry generated by `backend/app/demo/generator.py`. Timestamps are relative to "
             "the export date. Upload any file on the *Upload Security Data* page.", "",
             "| Dataset | Rows | Contents |", "|---|---|---|"]
    for name, spec in DATASETS.items():
        recs = dataset_records(name)
        aliases = name == "mixed"
        (OUT / f"{name}.csv").write_text(to_csv(recs, aliases), encoding="utf-8", newline="")
        (OUT / f"{name}.json").write_text(to_json(recs, aliases), encoding="utf-8")
        lines.append(f"| `{name}` | {len(recs)} | {spec['description']} |")
        print(f"{name}: {len(recs)} records")
    (OUT / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
