"""Threat hunting: structured hunt specifications, execution over stored telemetry, and NL translation.

A hunt spec is plain JSON (validated here), so a hunt can be written by an analyst, generated by the
language model through the `run_hunt` tool, or produced by the rule-based translator below.
"""

import re
from collections import Counter, defaultdict
from datetime import datetime, timedelta

from sqlalchemy import and_, or_, select
from sqlalchemy.orm import Session

from app.database.session import utcnow
from app.detection.base import is_off_hours
from app.ingestion.normalizer import is_external_ip, is_internal_ip
from app.models import AnomalyResult, Event, Host
from app.services.entity_risk import PRIV_PATTERNS

EVENT_TYPES = ("authentication", "process", "file", "network", "privilege", "other")
BEHAVIORS = {
    "new_source_for_user": "user authenticates from a source IP not seen for that user earlier in the data",
    "off_hours": "event occurs outside the workspace business hours",
    "rare_destination": "destination (IP or domain) contacted by at most 2 events in the whole workspace",
    "new_destination_for_host": "host contacts a destination it never contacted earlier in the data",
    "first_seen_process": "process name seen on the host for the first time",
    "external_destination": "destination is outside private address ranges (or a domain)",
    "large_transfer": "10 MB or more transferred in one event",
}
MAX_SCAN = 50_000


class HuntError(ValueError):
    pass


def _as_list(v) -> list[str]:
    if v is None or v == "":
        return []
    if isinstance(v, str):
        return [v]
    return [str(x) for x in v][:50]


def validate_spec(spec: dict) -> dict:
    if not isinstance(spec, dict):
        raise HuntError("Hunt specification must be an object")
    out: dict = {}
    t = spec.get("time") or {"last_hours": 24}
    if not isinstance(t, dict):
        raise HuntError("time must be an object")
    if t.get("all"):
        out["time"] = {"all": True}
    elif t.get("last_hours") is not None:
        hours = float(t["last_hours"])
        if not 0 < hours <= 24 * 365:
            raise HuntError("time.last_hours must be between 0 and 8760")
        out["time"] = {"last_hours": hours}
    else:
        out["time"] = {k: str(t[k]) for k in ("start", "end") if t.get(k)}
        if not out["time"]:
            out["time"] = {"last_hours": 24}
    if t.get("hour_from") is not None and t.get("hour_to") is not None:
        out["time"]["hour_from"], out["time"]["hour_to"] = int(t["hour_from"]) % 24, int(t["hour_to"]) % 24
    types = _as_list(spec.get("event_types"))
    bad = [x for x in types if x not in EVENT_TYPES]
    if bad:
        raise HuntError(f"Unknown event types: {', '.join(bad)}")
    out["event_types"] = types
    for key in ("actions", "users", "hosts", "ips", "text_any", "text_all", "processes"):
        out[key] = [x.strip() for x in _as_list(spec.get(key)) if x.strip()]
    if spec.get("status") not in (None, "", "success", "failure"):
        raise HuntError("status must be success or failure")
    out["status"] = spec.get("status") or None
    scope = spec.get("entity_scope") or {}
    out["entity_scope"] = {"privileged_users": bool(scope.get("privileged_users")), "servers": bool(scope.get("servers"))}
    behaviors = _as_list(spec.get("behaviors"))
    bad = [b for b in behaviors if b not in BEHAVIORS]
    if bad:
        raise HuntError(f"Unknown behaviors: {', '.join(bad)}. Allowed: {', '.join(BEHAVIORS)}")
    out["behaviors"] = behaviors
    seq = spec.get("followed_by")
    if seq:
        if not isinstance(seq, dict):
            raise HuntError("followed_by must be an object")
        sub = validate_spec({**seq, "time": {"all": True}, "followed_by": None})
        within = int(seq.get("within_minutes", 30))
        if not 1 <= within <= 1440:
            raise HuntError("followed_by.within_minutes must be between 1 and 1440")
        out["followed_by"] = {**{k: sub[k] for k in ("event_types", "actions", "status", "text_any", "behaviors")},
                              "internal_destination": bool(seq.get("internal_destination")),
                              "within_minutes": within, "same": seq.get("same") if seq.get("same") in ("user", "host") else "host"}
    out["above_baseline"] = bool(spec.get("above_baseline"))
    out["group_by"] = spec.get("group_by") if spec.get("group_by") in ("user", "host", "source_ip", "destination_ip") else None
    out["limit"] = max(1, min(int(spec.get("limit", 100)), 500))
    return out


def describe(spec: dict) -> list[dict]:
    lines = []
    t = spec["time"]
    if t.get("all"):
        lines.append({"label": "Time", "value": "All stored data"})
    elif t.get("last_hours"):
        lines.append({"label": "Time", "value": f"Last {t['last_hours']:g} hours of data"})
    else:
        lines.append({"label": "Time", "value": f"{t.get('start', 'beginning')} → {t.get('end', 'now')}"})
    if "hour_from" in t:
        lines.append({"label": "Time of day", "value": f"{t['hour_from']:02d}:00–{t['hour_to']:02d}:00 UTC"})
    if spec["event_types"]:
        lines.append({"label": "Event types", "value": ", ".join(spec["event_types"])})
    for key, label in (("actions", "Actions"), ("users", "Users"), ("hosts", "Hosts"), ("ips", "IP addresses"),
                       ("processes", "Processes"), ("text_any", "Contains any of"), ("text_all", "Contains all of")):
        if spec[key]:
            lines.append({"label": label, "value": ", ".join(spec[key])})
    if spec["status"]:
        lines.append({"label": "Outcome", "value": spec["status"]})
    scope = [k.replace("_", " ") for k, v in spec["entity_scope"].items() if v]
    if scope:
        lines.append({"label": "Entity", "value": ", ".join(scope)})
    for b in spec["behaviors"]:
        lines.append({"label": "Behavior", "value": BEHAVIORS[b]})
    if spec.get("followed_by"):
        f = spec["followed_by"]
        what = ", ".join(f["event_types"] or ["any event"]) + (" to internal destinations" if f["internal_destination"] else "")
        lines.append({"label": "Followed by", "value": f"{what} within {f['within_minutes']} min on the same {f['same']}"})
    if spec["above_baseline"]:
        lines.append({"label": "Anomaly", "value": "entity-day flagged above behavioral baseline"})
    return lines


def _time_bounds(db: Session, ws: int, t: dict) -> tuple[datetime | None, datetime | None]:
    from app.ingestion.normalizer import parse_timestamp

    if t.get("all"):
        return None, None
    if t.get("last_hours"):
        latest = db.scalar(select(Event.timestamp).where(Event.workspace_id == ws).order_by(Event.timestamp.desc()).limit(1))
        end = latest or utcnow()
        return end - timedelta(hours=t["last_hours"]), None
    start = parse_timestamp(t.get("start")) if t.get("start") else None
    end = parse_timestamp(t.get("end")) if t.get("end") else None
    return start, end


def _matches_basic(e: Event, spec: dict) -> bool:
    text = " ".join(filter(None, [e.process, e.command, e.resource, e.action])).lower()
    if spec["text_any"] and not any(x.lower() in text for x in spec["text_any"]):
        return False
    if spec["text_all"] and not all(x.lower() in text for x in spec["text_all"]):
        return False
    if spec["processes"] and not any(p.lower() in (e.process or "").lower() for p in spec["processes"]):
        return False
    return True


def run(db: Session, workspace_id: int, raw_spec: dict, business_hours: tuple[int, int] = (7, 20)) -> dict:
    spec = validate_spec(raw_spec)
    ws = workspace_id
    start, end = _time_bounds(db, ws, spec["time"])
    conds = [Event.workspace_id == ws]
    if start:
        conds.append(Event.timestamp >= start)
    if end:
        conds.append(Event.timestamp <= end)
    if spec["event_types"]:
        conds.append(Event.event_type.in_(spec["event_types"]))
    if spec["actions"]:
        conds.append(or_(*[Event.action.ilike(f"%{a}%") for a in spec["actions"]]))
    if spec["status"]:
        conds.append(Event.status == spec["status"])
    if spec["users"]:
        conds.append(Event.user.in_([u.lower() for u in spec["users"]]))
    if spec["hosts"]:
        conds.append(Event.host.in_([h.upper() for h in spec["hosts"]]))
    if spec["ips"]:
        conds.append(or_(Event.source_ip.in_(spec["ips"]), Event.destination_ip.in_(spec["ips"])))
    if spec["text_any"]:
        conds.append(or_(*[or_(Event.command.ilike(f"%{x}%"), Event.process.ilike(f"%{x}%"),
                               Event.resource.ilike(f"%{x}%")) for x in spec["text_any"]]))
    rows = db.scalars(select(Event).where(and_(*conds)).order_by(Event.timestamp).limit(MAX_SCAN)).all()
    scanned = len(rows)
    rows = [e for e in rows if _matches_basic(e, spec)]
    t = spec["time"]
    if "hour_from" in t:
        hf, ht = t["hour_from"], t["hour_to"]

        def in_hours(hour: int) -> bool:
            return hf <= hour < ht if hf < ht else (hour >= hf or hour < ht)

        rows = [e for e in rows if in_hours(e.timestamp.hour)]
    scope = spec["entity_scope"]
    if scope["privileged_users"]:
        priv = {u for (u,) in db.execute(select(Event.user).where(Event.workspace_id == ws, Event.user.is_not(None)).distinct())
                if any(p in u for p in PRIV_PATTERNS)}
        priv |= {e.user for e in db.scalars(select(Event).where(Event.workspace_id == ws,
                                                                 Event.action == "special_privileges_assigned"))}
        rows = [e for e in rows if e.user in priv]
    if scope["servers"]:
        servers = {h.hostname for h in db.query(Host).filter(Host.workspace_id == ws, Host.criticality.in_(["high", "critical"]))}
        rows = [e for e in rows if e.host in servers]

    behaviors = spec["behaviors"]
    if behaviors:
        history = None
        if {"new_source_for_user", "new_destination_for_host", "first_seen_process", "rare_destination"} & set(behaviors):
            history = db.execute(select(Event.id, Event.timestamp, Event.user, Event.host, Event.source_ip, Event.destination_ip,
                                        Event.resource, Event.process, Event.event_type)
                                 .where(Event.workspace_id == ws).order_by(Event.timestamp, Event.id)).all()
        first_src: dict[tuple, datetime] = {}
        first_dst: dict[tuple, datetime] = {}
        first_proc: dict[tuple, datetime] = {}
        dst_count: Counter = Counter()
        for h in history or []:
            dest = h.destination_ip or (h.resource.lower() if h.event_type == "network" and h.resource else None)
            if h.user and h.source_ip and h.event_type == "authentication":
                first_src.setdefault((h.user, h.source_ip), h.timestamp)
            if h.host and dest:
                first_dst.setdefault((h.host, dest), h.timestamp)
            if h.host and h.process:
                first_proc.setdefault((h.host, h.process.lower()), h.timestamp)
            if dest:
                dst_count[dest] += 1
        first_auth: dict[str, datetime] = {}
        for (u, _), ts in first_src.items():
            first_auth[u] = min(ts, first_auth.get(u, ts))

        def keep(e: Event) -> bool:
            dest = e.destination_ip or (e.resource.lower() if e.event_type == "network" and e.resource else None)
            for b in behaviors:
                if b == "off_hours" and not is_off_hours(e.timestamp, business_hours):
                    return False
                if b == "new_source_for_user":
                    if not (e.user and e.source_ip and first_src.get((e.user, e.source_ip)) == e.timestamp
                            and first_auth.get(e.user, e.timestamp) < e.timestamp):
                        return False
                if b == "new_destination_for_host" and not (e.host and dest and first_dst.get((e.host, dest)) == e.timestamp):
                    return False
                if b == "first_seen_process" and not (e.host and e.process and first_proc.get((e.host, e.process.lower())) == e.timestamp):
                    return False
                if b == "rare_destination" and not (dest and dst_count[dest] <= 2):
                    return False
                if b == "external_destination" and not (is_external_ip(e.destination_ip) or (not e.destination_ip and dest and "." in dest)):
                    return False
                if b == "large_transfer" and not (e.bytes and e.bytes >= 10_000_000):
                    return False
            return True

        rows = [e for e in rows if keep(e)]

    if spec["above_baseline"]:
        flagged = {(a.entity_type, a.entity, a.window_start.date()) for a in
                   db.query(AnomalyResult).filter_by(workspace_id=ws, is_anomalous=True)}
        rows = [e for e in rows if ("user", e.user, e.timestamp.date()) in flagged or ("host", e.host, e.timestamp.date()) in flagged]

    sequences = []
    if spec.get("followed_by") and rows:
        f = spec["followed_by"]
        same = f["same"]
        window = timedelta(minutes=f["within_minutes"])
        lo, hi = rows[0].timestamp, rows[-1].timestamp + window
        cand_conds = [Event.workspace_id == ws, Event.timestamp >= lo, Event.timestamp <= hi]
        if f["event_types"]:
            cand_conds.append(Event.event_type.in_(f["event_types"]))
        if f["status"]:
            cand_conds.append(Event.status == f["status"])
        cands = db.scalars(select(Event).where(and_(*cand_conds)).order_by(Event.timestamp).limit(MAX_SCAN)).all()
        cands = [c for c in cands if _matches_basic(c, {**f, "text_all": [], "processes": []})
                 and (not f["internal_destination"] or is_internal_ip(c.destination_ip))]
        by_key = defaultdict(list)
        for c in cands:
            by_key[getattr(c, same)].append(c)
        kept = []
        for e in rows:
            follow = [c for c in by_key.get(getattr(e, same), []) if e.timestamp < c.timestamp <= e.timestamp + window and c.id != e.id]
            if follow:
                kept.append(e)
                sequences.append({"first": _brief(e), "followed_by": [_brief(c) for c in follow[:5]],
                                  "follow_count": len(follow)})
        rows = kept

    total = len(rows)
    groups = []
    if spec["group_by"]:
        c = Counter(getattr(e, spec["group_by"]) for e in rows if getattr(e, spec["group_by"]))
        groups = [{"key": k, "count": n} for k, n in c.most_common(25)]
    entities = {
        "users": [k for k, _ in Counter(e.user for e in rows if e.user).most_common(15)],
        "hosts": [k for k, _ in Counter(e.host for e in rows if e.host).most_common(15)],
        "ips": [k for k, _ in Counter(ip for e in rows for ip in (e.source_ip, e.destination_ip) if ip).most_common(15)],
    }
    return {
        "spec": spec, "description": describe(spec), "scanned": scanned, "total": total,
        "truncated_scan": scanned >= MAX_SCAN, "groups": groups, "entities": entities,
        "events": [_brief(e) for e in rows[: spec["limit"]]], "sequences": sequences[:50],
        "time_range": {"start": start.isoformat() + "Z" if start else None, "end": end.isoformat() + "Z" if end else None},
    }


def _brief(e: Event) -> dict:
    return {"id": e.id, "event_uid": e.event_uid, "timestamp": e.timestamp.isoformat() + "Z", "event_type": e.event_type,
            "action": e.action, "status": e.status, "user": e.user, "host": e.host, "source_ip": e.source_ip,
            "destination_ip": e.destination_ip, "process": e.process, "command": (e.command or "")[:240] or None,
            "resource": (e.resource or "")[:200] or None, "bytes": e.bytes, "severity": e.severity}


# ---------------------------------------------------------------------------------- rule-based translation
_KEYWORDS = [
    (r"\b(log ?ins?|logons?|sign[- ]?ins?|authenticat\w*|credentials?)\b", {"event_types": ["authentication"]}),
    (r"\bfailed\b|\bfailures?\b|\bunsuccessful\b", {"status": "failure"}),
    (r"\bsuccessful\b|\bsucceeded\b", {"status": "success"}),
    (r"\bpowershell\b|\bpwsh\b", {"text_any": ["powershell"]}),
    (r"\bprocess(es)?\b|\bexecut\w*|\bcommands?\b", {"event_types": ["process"]}),
    (r"\bfiles?\b|\bshares?\b|\bdocuments?\b", {"event_types": ["file"]}),
    (r"\boutbound\b|\bconnections?\b|\bnetwork\b|\btraffic\b|\bcommunicat\w*|\buploads?\b|\btransfers?\b",
     {"event_types": ["network"]}),
    (r"\bprivilege changes?\b|\bgroup (changes?|additions?|membership)\b|\badmin group\b", {"event_types": ["privilege"]}),
    (r"\bnew (locations?|sources?|ips?)\b|\bpreviously unseen\b|\bunusual (locations?|sources?)\b",
     {"behaviors": ["new_source_for_user"], "event_types": ["authentication"]}),
    (r"outside (of )?(normal|business|working) hours|\boff[- ]hours\b|\bat night\b|\bovernight\b",
     {"behaviors": ["off_hours"]}),
    (r"\brare\b", {"behaviors": ["rare_destination"]}),
    (r"\bnew destinations?\b|\bnever (contacted|seen)\b", {"behaviors": ["new_destination_for_host"]}),
    (r"\bfirst[- ]seen process|\bnew process", {"behaviors": ["first_seen_process"]}),
    (r"\bexternal\b|\binternet\b|\boutside the (network|organi[sz]ation)\b", {"behaviors": ["external_destination"]}),
    (r"\blarge\b|\bbig\b|\bhigh[- ]volume\b", {"behaviors": ["large_transfer"]}),
    (r"\bprivileged\b|\badmins?\b|\badministrators?\b", {"entity_scope": {"privileged_users": True}}),
    (r"\bservers?\b|\bdomain controllers?\b|\bdatabases?\b", {"entity_scope": {"servers": True}}),
    (r"\bunusual\b|\banomal\w*|\babove baseline\b|\bstrange\w*", {"above_baseline": True}),
    (r"\bdiscovery\b|\breconnaissance\b|\brecon\b", {"text_any": ["whoami", "net user", "net group", "nltest", "systeminfo", "ipconfig"]}),
    (r"\bencoded\b|\bobfuscat\w*", {"text_any": ["-enc", "frombase64string"]}),
]


def translate(text: str) -> dict:
    """Rule-based natural-language → hunt spec translation (keyword rules; shown to the analyst for editing)."""
    q = text.lower()
    spec: dict = {"event_types": [], "text_any": [], "behaviors": [], "entity_scope": {}, "time": {"all": True}}  # no time stated → all telemetry
    matched = []
    main, follow = q, ""
    if re.search(r"\bfollowed by\b|\bthen\b", q):
        main, follow = re.split(r"\bfollowed by\b|\bthen\b", q, maxsplit=1)
    for pattern, patch in _KEYWORDS:
        if re.search(pattern, main):
            matched.append(pattern)
            for k, v in patch.items():
                if isinstance(v, list):
                    spec[k] = list(dict.fromkeys(spec.get(k, []) + v))
                elif isinstance(v, dict):
                    spec[k] = {**spec.get(k, {}), **v}
                else:
                    spec[k] = v
    if m := re.search(r"last (\d+) ?(hours?|h|days?|d)\b", q):
        n = int(m.group(1))
        spec["time"] = {"last_hours": n * (24 if m.group(2).startswith("d") else 1)}
    elif re.search(r"\btoday\b|\blast 24 hours\b", q):
        spec["time"] = {"last_hours": 24}
    elif re.search(r"\bthis week\b|\blast week\b|\blast 7 days\b", q):
        spec["time"] = {"last_hours": 168}
    elif re.search(r"\bever\b|\ball (time|data)\b|\bhistor\w*", q):
        spec["time"] = {"all": True}
    if m := re.search(r"between (\d{1,2}):?(\d{2})? and (\d{1,2}):?(\d{2})?", q):
        spec["time"]["hour_from"], spec["time"]["hour_to"] = int(m.group(1)), int(m.group(3))
    for ip in re.findall(r"\b\d{1,3}(?:\.\d{1,3}){3}\b", text):
        spec.setdefault("ips", []).append(ip)
    if follow:
        sub = translate(follow)
        spec["followed_by"] = {"event_types": sub["event_types"], "text_any": sub.get("text_any", []),
                               "internal_destination": bool(re.search(r"\binternal\b", follow)), "within_minutes": 30,
                               "same": "host"}
    if "authentication" in spec["event_types"] and "network" in spec["event_types"] and "new_source_for_user" in spec["behaviors"]:
        spec["event_types"].remove("network")
    if spec["behaviors"] and any(b in spec["behaviors"] for b in ("rare_destination", "new_destination_for_host",
                                                                  "external_destination", "large_transfer")):
        if "network" not in spec["event_types"]:
            spec["event_types"].append("network")
    spec["group_by"] = "user" if spec["event_types"] == ["authentication"] else "host"
    return {"spec": validate_spec(spec), "method": "rule-based", "matched_rules": len(matched)}
